/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LowLevelUSB */

#ifndef _Included_LowLevelUSB
#define _Included_LowLevelUSB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LowLevelUSB
 * Method:    initializeUSB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LowLevelUSB_initializeUSB
  (JNIEnv *, jobject, jint);

/*
 * Class:     LowLevelUSB
 * Method:    fetchData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_LowLevelUSB_fetchData
  (JNIEnv *, jobject);

/*
 * Class:     LowLevelUSB
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LowLevelUSB_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
